---
- hosts: localhost
  connection: local
  gather_facts: false
  vars:
    checksum: ""
    # downloadURL: "https://api.access.redhat.com/management/v1/images/{{ mychecksum }}/download"
    offline_token: eyJhbGciOiJIUzI1NiIsInR5cCIgOiAiSldUIiwia2lkIiA6ICJhZDUyMjdhMy1iY2ZkLTRjZjAtYTdiNi0zOTk4MzVhMDg1NjYifQ.eyJpYXQiOjE2MzA5MDY5MjYsImp0aSI6ImUxMGUyYTMxLWQ3YjgtNDg0MC04ZGFkLTFjMjkyZWIxZTZkOSIsImlzcyI6Imh0dHBzOi8vc3NvLnJlZGhhdC5jb20vYXV0aC9yZWFsbXMvcmVkaGF0LWV4dGVybmFsIiwiYXVkIjoiaHR0cHM6Ly9zc28ucmVkaGF0LmNvbS9hdXRoL3JlYWxtcy9yZWRoYXQtZXh0ZXJuYWwiLCJzdWIiOiJmOjUyOGQ3NmZmLWY3MDgtNDNlZC04Y2Q1LWZlMTZmNGZlMGNlNjpuaWNrcGF0bmUiLCJ0eXAiOiJPZmZsaW5lIiwiYXpwIjoicmhzbS1hcGkiLCJzZXNzaW9uX3N0YXRlIjoiYjY1YzZlMDEtYWM4Zi00YjYzLThhZTQtYTZlMmJjMmUxN2E1Iiwic2NvcGUiOiJvZmZsaW5lX2FjY2VzcyJ9.foZ14FE79jhW6_R0pcQkaQoTEVLS3oWssvAsAbOx0Qo
  tasks:
    - name: To get RH Access token
      shell: curl https://sso.redhat.com/auth/realms/redhat-external/protocol/openid-connect/token -d grant_type=refresh_token -d client_id=rhsm-api -d refresh_token={{ offline_token }} | jq --raw-output .access_token
      register: access_token

    - name: Print Access token token
      debug: 
        msg: "{{ access_token.stdout }}"

    - name: Calling API to get  all resources
      uri:
        url: https://api.access.redhat.com/management/v1/images/cset/rhel-8-for-x86_64-baseos-isos
        method: GET
        headers:
          Authorization: Bearer {{ access_token.stdout }}
          Accept: application/json
        body_format: json
        return_content : yes
      register: output

    - name: filtering checksum of rhel8.1-dvd-iso
      set_fact:
        checksum: "{{ item.checksum }}"
      when: item.filename == "rhel-8.1-x86_64-dvd.iso"
      loop: "{{ output.json.body }}"


    - name: Print checksum value
      debug: 
        msg: "{{ checksum }}"
    
    # - set_fact:
    #      mychecksum: "{{ checksum | string }}"


    # - name: To get Downloadeble URL
    #   uri:
    #     url: "{{ downloadURL }}"
    #     method: GET
    #     headers:
    #       Authorization: Bearer {{ access_token.stdout }}
    #       Accept: application/json
    #     body_format: json
    #     return_content : yes
    #   register: download_url


    # - name: Print download_url value
    #   debug: 
    #     msg: "{{ download_url }}"




---
  - name: downloading RHEL-8.1-DVD iso file
    get_url:
      url: "{{ download_url }}"
      dest: "{{ download_destination_path }}"
      client_key: "{{ redhat_entitlment_key }}"
      client_cert: "{{ redhat_entitlment_certificate }}"
      validate_certs: no
    async: 3600
    poll: 0
    register: downloaded_rhel_iso


  - name: Checking on async task - downloading RHEL-8.1-DVD iso file
    async_status:
        jid: "{{ item.ansible_job_id }}"
    register: rhel_iso_job_result
    until: rhel_iso_job_result.finished
    retries: 200
    delay: 20                  


    
    
