---
- hosts: localhost
  connection: local
  tasks:
    - name: Sending an email notification
      mail:
        host: "smtp.gmail.com"
        port: "587"
        username: "idmsubs@gslab.com"
        password: "eefncgnfzgvxjsvi"
        to: "User <nikhil.patne@gslab.com>"
        subject: "test"
        subtype: html
        body: "hello nikhil"
        secure: starttls
