---
- hosts: localhost
  connection: local
  tasks:
    - name: Copy file to datastore using delegate_to
      community.vmware.vsphere_copy:
        hostname: '{{ vcenter_hostname }}'
        username: '{{ vcenter_username }}'
        password: '{{ vcenter_password }}'
        src: /some/local/file
        datacenter: DC1 Someplace
        datastore: datastore1
        path: "/000ISO/nikhil.iso"
